---
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Download latest requirements from Microsoft"
  get_url:
    url: https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
    dest: "{{ requirements_path }}/requirements-azure.txt"
    mode: '0440'

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Install with pip3"
  pip:
    requirements: "{{ requirements_path }}/requirements-azure.txt"
